package com.app.customermanager.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data // Lombok annotation to generate boilerplate code like getters, setters, toString, equals, and hashCode methods
@Entity // Indicates that this class is an entity and is mapped to a database table
@Table(name = "customers") // Specifies the name of the table in the database
public class Customer {
    
    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key value will be generated by the database, using an auto-increment strategy
    private Integer id;
    private String firstname;
    private String lastname;
    private String email;
    private String address;

}
